package Oceanus.Tv.Service.ChannelScanManager.ChannelScanManagerDefinitions.DtvScanDefinitions;

/**
 * Created by sky057509 on 2016/9/6.
 */
public enum EN_DTV_SCAN_MODE {
    E_DTV_MANUAL_TUNE_MODE_DVB_T,
    E_DTV_MANUAL_TUNE_MODE_DVB_C,
    E_DTV_MANUAL_TUNE_MODE_ISDB,
    E_DTV_MANUAL_TUNE_MODE_ATSC,
    E_DTV_MANUAL_TUNE_MODE_DTMB,
    E_DTV_AUTO_TUNE_MODE_DVB_T,
    E_DTV_AUTO_TUNE_MODE_DVB_C,
    E_DTV_AUTO_TUNE_MODE_ISDB,
    E_DTV_AUTO_TUNE_MODE_ATSC,
    E_DTV_AUTO_TUNE_MODE_DTMB,
    E_DTV_TUNE_MODE_NIT_TABLE,
    E_DTV_TUNE_MODE_SATELLITE,
    E_DTV_TUNE_MODE_UNDEFINE
}
